CREATE TABLE IF NOT EXISTS `USER` (
  `ID_USER` int(11) NOT NULL,
  `USERNAME` varchar(200) NOT NULL,
  `ID_ROLE` int(11) NOT NULL,
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);
 
ALTER TABLE `USER` ADD PRIMARY KEY (`ID_USER`);
ALTER TABLE `USER` MODIFY `ID_USER` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `USER` ADD FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE)

CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID_ROLE` int(11) NOT NULL,
  `ROLE_NAME` varchar(200) NOT NULL,
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);
 
ALTER TABLE `ROLE` ADD PRIMARY KEY (`ID_ROLE`);
ALTER TABLE `ROLE` MODIFY `ID_ROLE` int(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE IF NOT EXISTS `SHIFT` (
  `ID_SHIFT` int(11) NOT NULL,
  `ID_USER` int(11) NOT NULL,
  `SHIFT_DATE` datetime NOT NULL,
  `WORK_START` datetime NOT NULL,
  `WORK_END` datetime NOT NULL,
  `IS_PUBLISHED` tinyint(1) NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` datetime NULL
);
 
ALTER TABLE `SHIFT` ADD PRIMARY KEY (`ID_SHIFT`);
ALTER TABLE `SHIFT` MODIFY `ID_SHIFT` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `SHIFT` ADD FOREIGN KEY (`ID_USER`) REFERENCES USER(`ID_USER`)